<a href="https://colab.research.google.com/github/Alissa-Ouspen/data201_alissa/blob/main/week1/assignment_2_r_to_python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Assignment -- R → Python Data Analysis Bridge (Week 1)

In [4]:
import numpy as np

## Part A:  &nbsp;Translation

Integers greater than 4 should be squared.  
Integers equal to or less than 4 should be added to 1.  
y should be [2, 4, 25, 49]  
and the output should be that the mean of y is 20.

In [12]:

x = np.array([1, 3, 5, 7])
y = np.where(x > 4, x**2, x + 1)
print(y)
np.mean(y)

[ 2  4 25 49]


np.float64(20.0)

[ 2  4 25 49]  
np.float64(20.0)

---

### Part B:  &nbsp; Lists vs NumPy Arrays

In [22]:
myList = []
for z in range(1,6):
  myList.append(z)
print(myList)

print(myList*2)

np.array(myList)*2


[1, 2, 3, 4, 5]
[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


array([ 2,  4,  6,  8, 10])

Multiplying the list by 2 doubles the list:  
extra values are created, which are the duplicates of the original.   

Multiplying the array by 2 doubles each value in the array.

---


### Part C:  &nbsp;Reflection  
Since Python is more versatile and is not just for math and statistics, it's necessary to specify which library (which tools) are needed for the task.  R is more geared towards data analysis and statistics.  It is meant for fast computations.  
Python has less data visualization capabilities and relies on html for visual formatting.  
However, each has its strengths, and it is advantageous to know how to use them both and to integrate them.

